<a href="https://colab.research.google.com/github/rkalladan/TensorLearn/blob/master/PytorchLearn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Tensor CPU Example

In [4]:
import torch

first_tens = torch.tensor([[12,10,11,9],[13,15,14,16]])
sec_tens = torch.tensor([[1,2,3,4],[5,6,7,8]])

add_tens = first_tens + sec_tens
print(add_tens)

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])


In [7]:
sub_tens = first_tens - sec_tens
print(sub_tens)
print(sub_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


Creating GPU Example

In [2]:
import torch
print(torch.__version__)

2.3.0+cu121


In [3]:
if torch.cuda.is_available() : device ="cuda"
else : device = "cpu"
print(device)

cuda


In [10]:
tens_a = torch.tensor([[12,10,11,9],[13,15,14,16]], device=device)
tens_b = torch.tensor([[1,2,3,4],[5,6,7,8]], device=device)
tens_multi = tens_a * tens_b
print(tens_multi) # We can see that which device it is executed(cuda:0)
print(torch.dtype.itemsize)

tensor([[ 12,  20,  33,  36],
        [ 65,  90,  98, 128]], device='cuda:0')
<attribute 'itemsize' of 'torch.dtype' objects>


Moving data between CPU & GPU