<a href="https://colab.research.google.com/github/rkalladan/TensorLearn/blob/master/PytorchLearn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Tensor CPU Example

In [4]:
import torch

first_tens = torch.tensor([[12,10,11,9],[13,15,14,16]])
sec_tens = torch.tensor([[1,2,3,4],[5,6,7,8]])

add_tens = first_tens + sec_tens
print(add_tens)

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])


In [7]:
sub_tens = first_tens - sec_tens
print(sub_tens)
print(sub_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


Creating GPU Example

In [2]:
import torch
print(torch.__version__)

2.3.0+cu121


In [3]:
if torch.cuda.is_available() : device ="cuda"
else : device = "cpu"
print(device)

cuda


In [10]:
tens_a = torch.tensor([[12,10,11,9],[13,15,14,16]], device=device)
tens_b = torch.tensor([[1,2,3,4],[5,6,7,8]], device=device)
tens_multi = tens_a * tens_b
print(tens_multi) # We can see that which device it is executed(cuda:0)
print(torch.dtype.itemsize)

tensor([[ 12,  20,  33,  36],
        [ 65,  90,  98, 128]], device='cuda:0')
<attribute 'itemsize' of 'torch.dtype' objects>


Moving data between CPU & GPU

In [1]:
import torch

# create a tensor
x = torch.tensor([5,10,15,10,25])
print("Tensor:", x)
# check tensor device (cpu/cuda)
print("Tensor device:", x.device)

Tensor: tensor([ 5, 10, 15, 10, 25])
Tensor device: cpu


In [3]:
print("CUDA GPU:", torch.cuda.is_available())
if torch.cuda.is_available():
   x = x.to("cuda:0")
   # or x=x.to("cuda")
print(x)

# now check the tensor device
print("Tensor device:", x.device)

CUDA GPU: True
tensor([ 5, 10, 15, 10, 25], device='cuda:0')
Tensor device: cuda:0


Different ways to create tensors

In [4]:
import torch
import numpy as np

In [5]:
# initialize a tensor from a Python list
tensor_from_list=torch.tensor([1,2,3,4,5])
# initialize a tensor from a tuple
tensor_from_tuple=torch.tensor((6,7,8,9,10))
print("Tensor from list:",tensor_from_list)
print("Tensor from tuple:",tensor_from_tuple)

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])


In [6]:
# initialize a tensor from a ndarray
tensor_from_array=torch.tensor(np.array([11,12,13,14,15]))
print("Tensor from array:",tensor_from_array)

Tensor from array: tensor([11, 12, 13, 14, 15])


Different functions for creating tensors:

torch.empty(), torch.ones(), and torch.zeros()

In [7]:
tensor_emp = torch.empty(3,4)
print("tensor_emp :",tensor_emp)
tensor_zeros = torch.zeros(3,4)
print("tensor_zeros :",tensor_zeros)
tensor_ones= torch.ones(3,4)
print("tensor_ones :",tensor_ones)

tensor_emp : tensor([[8.1919e-10, 1.0081e-08, 2.1666e-04, 3.2905e+21],
        [2.4828e-18, 3.1360e+27, 7.0800e+31, 3.1095e-18],
        [1.2250e+25, 7.0969e+22, 4.4260e+30, 7.2442e+22]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
# tensors initialized by size with random values
# returns a tensor filled with random numbers from a uniform distribution
tensor_rand_un = torch.rand(4,5)
print("tensor_rand_un :",tensor_rand_un)
# returns a tensor filled with random numbers from a normal distribution
tensor_rand_norm = torch.randn(4,5)
print("tensor_rand_norm :",tensor_rand_norm)
# returns a tensor filled with random integers generated uniformly
tensor_rand_int = torch.randint(5,10,(4,5))
print("tensor_rand_int :",tensor_rand_int)

tensor_rand_un : tensor([[0.5431, 0.3528, 0.2543, 0.7197, 0.6238],
        [0.8078, 0.2623, 0.2395, 0.8070, 0.3050],
        [0.4452, 0.8011, 0.1017, 0.1262, 0.0786],
        [0.6523, 0.1392, 0.1979, 0.3262, 0.4062]])
tensor_rand_norm : tensor([[-1.6015, -1.6611, -1.0017,  0.1179,  0.1585],
        [ 1.2788, -0.1559, -0.2752, -0.5508,  0.1388],
        [ 0.2057, -1.3987,  0.6037,  0.3495,  1.6670],
        [-0.6494,  0.3001,  1.4704, -0.9788, -0.0127]])
tensor_rand_int : tensor([[7, 7, 8, 5, 9],
        [7, 7, 7, 9, 6],
        [9, 8, 7, 6, 8],
        [8, 5, 9, 7, 5]])


In [9]:
# initialize a tensor of ones
tensor_ones = torch.ones_like(tensor_rand_int)
print(tensor_ones)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


**Tensor attributes**

knowing device location, datatype, dimension, and rank is very important

In [15]:
first_tensor = torch.tensor([1,2,3,4,5,6])
#torch.device indicates the tensor’s device location

print(first_tensor.device)
first_tensor.device


cpu


device(type='cpu')

In [14]:
#torch.dtype indicates the tensor’s data type
first_tensor.dtype

torch.int64

In [16]:
#torch.shape shows the tensor’s dimensions
first_tensor.shape

torch.Size([6])

In [17]:
#torch.ndim identifies the number of a tensor’s dimensions or rank
first_tensor.ndim

1

In [26]:
second_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(second_tensor.ndim)
print(second_tensor.shape)
print(second_tensor.device)
print(second_tensor.size())
print(second_tensor.requires_grad)

2
torch.Size([3, 3])
cpu
torch.Size([3, 3])
False
